FROM ruby:3.1.4-alpine3.18
RUN apk --update add build-base nodejs tzdata sqlite-libs libxslt-dev libxml2-dev imagemagick
ENV RAILS_ENV production
ENV REDIS_URL="redis://redis:6379/1"
COPY . /app
WORKDIR /app
RUN ["bundle", "install"]
RUN ["rake", "assets:clobber"]
RUN ["rails", "assets:precompile"]
RUN ["rake", "db:migrate"]
CMD ["foreman", "start", "-f", "Procfile.prod"]
