FROM ruby:3.1-alpine3.18
RUN apk --update add build-base nodejs tzdata postgresql-dev postgresql-client libxslt-dev libxml2-dev imagemagick
ENV RAILS_ENV=development
ENV REDIS_URL="redis://redis:6379/1"
CMD ["/bin/sh"]