version: '2'
services:
  rails:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - redis
    ports:
      - "80:3000"
  redis:
    image: redis:latest
